#!/usr/bin/env python3

import rospy
from nav_msgs.msg import OccupancyGrid
from geometry_msgs.msg import PointStamped
# Import the class you just shared (assuming it's in the same file or a local module)
from frontier_finder import FrontierDetector 

class FrontierNode:
    def __init__(self):
        rospy.init_node('frontier_explorer_node')

        # 1. Subscribers
        # We listen to the map generated by gmapping
        self.map_sub = rospy.Subscriber('/map', OccupancyGrid, self.map_callback)

        # 2. Publishers
        # This allows you to see the frontiers in RViz
        self.frontier_map_pub = rospy.Publisher('/detected_frontiers', OccupancyGrid, queue_size=1)
        
        self.detector = None

    def map_callback(self, msg):
        # Initialize detector once we have map metadata (width, height, etc.)
        if self.detector is None:
            self.detector = FrontierDetector(
                map_width=msg.info.width,
                map_height=msg.info.height,
                resolution=msg.info.resolution,
                origin_x=msg.info.origin.position.x,
                origin_y=msg.info.origin.position.y
            )

        # 3. Use the detector
        # raw_data is the 1D tuple from the OccupancyGrid message
        centroids, frontier_map_data = self.detector.detect_frontiers(msg.data)

        # 4. Publish the debug map (visualization)
        self.publish_frontier_map(msg, frontier_map_data)

        # 5. Output the results
        rospy.loginfo(f"Found {len(centroids)} frontier clusters.")
        for i, (wx, wy) in enumerate(centroids):
            print(f"Frontier {i}: World Coordinates x={wx:.2f}, y={wy:.2f}")

    def publish_frontier_map(self, original_msg, debug_data):
        """Helper to package the 1D list back into a ROS OccupancyGrid"""
        f_map = OccupancyGrid()
        f_map.header.stamp = rospy.Time.now()
        f_map.header.frame_id = original_msg.header.frame_id
        f_map.info = original_msg.info # Keep same dimensions and resolution
        f_map.data = debug_data
        self.frontier_map_pub.publish(f_map)

if __name__ == '__main__':
    try:
        node = FrontierNode()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass